---
title: "Prediction of the Result of 2019 Canadian Federal Election if Everyone can Vote"
author: "YUWEN WU"
date: "December 22, 2020"
reference: "reference.bib"
output: pdf_document
---
## Keywords
Trudeau, Scheer, 2019 Canadian Federal Election, Liberal, , Conservative, forecasting, Multilevel regression with post-stratification

## Abstract
The Canadian election is an important event in Canada. The goal is to predict Trudeau or Scheer would win the election, in other words which party will win the election. I forecast the election by the survey data using a multilevel regression with post-stratification. Liberal gains 157 seats and Conservative gains 21 seats.
  

## Introduction

 Through the 2019 Canadian Federal election, Trudeau could go back to the Prime Minister’s Office. He would lead Liberal minority government. The Liberal lost 20 seat, but its opposite Conservative get 26 seats. The total turnout decreased for 68% to 62%. There are lots of people support Liberal in Ontario @election2. 
  
  In order to do prediction on our interest: the Result of 2019 Canadian Federal Election if Everyone can Vote, we combine individual survey data from CES and census data from 2016 Stat Canada Eduaction Census to use a multilevel regression with post-stratification. We also create a Bayesian logistic regression model. The outcome we found is that xxx will win this election.

  This work will continue to analyze the data from CES and 2016 Stat Canada Eduaction Census. Firstly, we summarize features of two dataset and visualize some variables of interest to our model. Next, we describe the features of our model and post-stratification process. Finally, we discuss our prediction of the result of 2019 Canadian Federal Election if "everyone" voted. And we discuss the weaknesses of the project, also give suggestions for the further study.

## Data

```{r, include=FALSE}
knit::opts_chunk$set(echo=TRUE)
install.packages("devtools")
library(devtools)
devtools::install_github("hodgettsp/cesR")
library(cesR)
install.packages("labelled")
library(labelled)

get_ces("ces2019_web")

ces2019_web <- to_factor(ces2019_web)
head(ces2019_web)

library(tidyverse)
Select <- ces2019_web %>% select(cps19_gender, cps19_province, cps19_citizenship, cps19_education, cps19_age, cps19_votechoice)

#census

```
###Survey data:
The survey data is about 2019 Canadian election.

The figure1 shows the relationship between age and seats of election, from that we can clearly find age cannot affect seats of election.


The figure2 shows the relationship between education and the seats of election, from that we can see that education affect the seats of election slightly.


The figure3 shows the relationship between the citizenship and the seats of election, from that we can see citizenship affect the seats of election seriously. 


###Census data:
The census data  comes from the 2017 General Social Survey (GSS) on the Family. The 2017 GSS, coordinated
from February 2, 2017 to November 30, 2017, is a sample survey of cross-sectional survey design.





## Model
We used multilevel regression model with the response variable being vote for Party of federal or not. The model could clearly predict the process of election, which mean which part get the seats, and then to show which party win the election.
At first, we fit a multilevel regression model with my survey data about 2019 Canadian election.

Then, we use the model to obtain the prediction of Canadian election.
Then, we apply the post-stratification.

## Results
I use the multilevel regression model to find the ROC curve. The AUC is 0.xx
indicating sufficiently good model prediction power. The point estimate of the probability of the party of federal winning the election, the 95% confidence interval around it.

According to my model, we could estimate the possibility of vote to the election of each party.

In the figure4, it show the percentage of supporting rate to Trudeau and Scheer. And then, I found that Trudeau and the party of federal won he election by a slightly advantage.

## Discussion
###1. Conclusion
We use the survey data about the 2019 Canadian Federal Election and the post-stratification data comes from the 2017 General Social Survey (GSS) on the Family to estimate the probability of the party of federal win the 2019 Canadian Election. We use a multilevel regression with post-stratification with variables gender, province, citizenship, education, age, votechoice. I use that to predict the probability of the party of federal to win the Canadian election. Finally, we get the probability is 67%



###2. Limitations and Weaknesses

The major limitation is that I could try to filter my data first and this would make my model easy to predict. Also, I think the data is not enough to make the great multilevel regression.



###3. Future Work
In the future, I will improve my model and make it be more efficient. Also, I would choose the data carefully and to find which variables are straight affecting the possibility of voting. FInally, I would make the model predict the value accurately.


## Appendix
All codes could be found here: https://github.com/Johnston0618/FP-sta304
@election1
@ces
@tidyverse
@R

## References
